  #cloud-config
  timezone: EST
  # forked version of : https://github.com/dtag-dev-sec/tpotce/blob/master/cloud/terraform/cloud-init.yaml
  package_update: true
  package_upgrade: true
  package_reboot_if_required: true

  packages:
    - git
    - htop
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

  runcmd:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    - sudo apt update
    - apt-cache policy docker-ce
    - sudo apt install -y docker-ce
    - sudo systemctl status docker
    - sudo service ntp stop
    - sudo service ntp start
    - sudo docker run -p 8080:8080 -t webgoat/webgoat-8.0
    - sudo docker run --rm -it -p 20:20 -p 21:21 -p 80:80 -p 443:443 -p 4848:4848 -p 6000:6000 -p 6060:6060 -p 7000:7000 -p 7181:7181 -p 7547:7547 -p 8000:8000 -p 8008:8008 -p 8020:8020 -p 8081:8080 -p 8400:8400 vulnerables/metasploit-vulnerability-emulator
    - docker run --rm -it -p 81:80 cyrivs89/web-dvws
    - docker run --rm -p 3000:3000 bkimminich/juice-shop
    - docker run --name webgoat -d --restart unless-stopped -p 6661:8080 -t santosomar/webgoat
    - docker run --name juice-shop --restart unless-stopped -d -p 6662:3000 santosomar/juice-shop
    - docker run --name dvwa --restart unless-stopped -itd -p 6663:80 santosomar/dvwa
    - docker run --name mutillidae_2 --restart unless-stopped -d -p 6664:80 santosomar/mutillidae_2
    - docker run --name bwapp2 --restart unless-stopped -d -p 6665:80 santosomar/bwapp
    - docker run --name dvna --restart unless-stopped -d -p 6666:9090 santosomar/dvna
    - docker run --name hackazon -d --restart unless-stopped -p 6667:80 santosomar/hackazon
    - docker run --name hackme-rtov -d --restart unless-stopped -p 9000:80 santosomar/hackme-rtov