#cloud-config
timezone: EST
# forked version of : https://github.com/dtag-dev-sec/tpotce/blob/master/cloud/terraform/cloud-init.yaml
package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - git
  - htop
  - ntp

runcmd:
  - sudo ntpd -gq
  - sudo service ntp start
  - git clone https://github.com/facebook/fbctf /root/fbctf
  - cd /root/fbctf
  - . ./extra/lib.sh
  - quick_setup install dev
