#cloud-config
timezone: EST
# forked version of : https://github.com/dtag-dev-sec/tpotce/blob/master/cloud/terraform/cloud-init.yaml
package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - git
  - htop

runcmd:
  - apt update
  - git clone https://github.com/secdevops-cuse/tpotce /root/tpot
  - /root/tpot/iso/installer/install.sh --type=auto --conf=/root/tpotce/iso/installer/tpot.conf.dist
  - /sbin/shutdown -r +5