#cloud-config
timezone: EST

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - git
  - htop

runcmd:
  - apt update
  - git clone https://github.com/secdevops-cuse/tpotce /root/tpot
  - /root/tpot/iso/installer/install.sh --type=auto --conf=/root/tpotce/iso/installer/tpot.conf.dist
  - /sbin/shutdown -r +5

# The contents of tpot.conf will be base64 encoded and appended to this file
# via the terraform configuration in main.tf
#
# Make sure there are no trailing new lines after "permissions" below
write_files:
  - encoding: b64
    owner: root:root
    path: /root/tpot.conf
    permissions: '0600'