version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  circle-compare-url: iynere/compare-url@1.2.0

jobs:
  test:
    <<: *default_config
    steps:
        - circle-compare-url/reconstruct
        - circle-compare-url/use:
            step-name: Compare URL Create Step
            attach-workspace: true
        - slack/notify:
                  channel: cicd
                  color: '#42e2f4'
                  message: A $CIRCLE_JOB job has started to test \n\n Compare URL -> $CIRCLE_COMPARE_URL
                  webhook: '${SLACK_WEBHOOK}'
        - slack/status:
                  channel: cicd
                  mentions: 'cappetta'
                  webhook: '${SLACK_WEBHOOK}'

workflows:
  version: 2
  development_build:
    jobs:
      - test
